const CONSTELLATIONS = [
    { "name": "Andromeda", "abbr": "AND", "ra": 14.4, "dec": 38.6, "name_he": "אנדרומדה" },
    { "name": "Antlia", "abbr": "ANT", "ra": 156.6, "dec": -33.3, "name_he": "משאבה" },
    { "name": "Apus", "abbr": "APS", "ra": 240.2, "dec": -76.8, "name_he": "ציפור גן עדן" },
    { "name": "Aquarius", "abbr": "AQR", "ra": 334.8, "dec": -11.1, "name_he": "דלי" },
    { "name": "Aquila", "abbr": "AQL", "ra": 296.2, "dec": 3.4, "name_he": "נשר" },
    { "name": "Ara", "abbr": "ARA", "ra": 258.1, "dec": -56.3, "name_he": "מזבח" },
    { "name": "Aries", "abbr": "ARI", "ra": 40.7, "dec": 20.8, "name_he": "טלה" },
    { "name": "Auriga", "abbr": "AUR", "ra": 90.4, "dec": 42.0, "name_he": "עגלון" },
    { "name": "Boötes", "abbr": "BOO", "ra": 222.0, "dec": 31.0, "name_he": "רועה דובים" },
    { "name": "Caelum", "abbr": "CAE", "ra": 70.5, "dec": -38.6, "name_he": "אזמל" },
    { "name": "Camelopardalis", "abbr": "CAM", "ra": 88.9, "dec": 69.4, "name_he": "ג'ירף" },
    { "name": "Cancer", "abbr": "CNC", "ra": 130.6, "dec": 20.0, "name_he": "סרטן" },
    { "name": "Canes Venatici", "abbr": "CVN", "ra": 196.8, "dec": 40.1, "name_he": "כלבי ציד" },
    { "name": "Canis Major", "abbr": "CMA", "ra": 102.5, "dec": -22.7, "name_he": "כלב גדול" },
    { "name": "Canis Minor", "abbr": "CMI", "ra": 114.3, "dec": 6.4, "name_he": "כלב קטן" },
    { "name": "Capricornus", "abbr": "CAP", "ra": 316.5, "dec": -18.0, "name_he": "גדי" },
    { "name": "Carina", "abbr": "CAR", "ra": 130.5, "dec": -63.3, "name_he": "שדרית" },
    { "name": "Cassiopeia", "abbr": "CAS", "ra": 17.8, "dec": 62.2, "name_he": "קסיופאה" },
    { "name": "Centaurus", "abbr": "CEN", "ra": 196.2, "dec": -47.3, "name_he": "קנטאור" },
    { "name": "Cepheus", "abbr": "CEP", "ra": 330.6, "dec": 71.0, "name_he": "קפאוס" },
    { "name": "Cetus", "abbr": "CET", "ra": 24.3, "dec": -7.2, "name_he": "לווייתן" },
    { "name": "Chamaeleon", "abbr": "CHA", "ra": 161.4, "dec": -79.2, "name_he": "זיקית" },
    { "name": "Circinus", "abbr": "CIR", "ra": 223.6, "dec": -63.0, "name_he": "מחוגה" },
    { "name": "Columba", "abbr": "COL", "ra": 86.8, "dec": -35.1, "name_he": "יונה" },
    { "name": "Coma Berenices", "abbr": "COM", "ra": 192.1, "dec": 23.3, "name_he": "שערות ברניקי" },
    { "name": "Corona Australis", "abbr": "CRA", "ra": 284.4, "dec": -41.1, "name_he": "עטרה דרומית" },
    { "name": "Corona Borealis", "abbr": "CRB", "ra": 236.4, "dec": 32.6, "name_he": "עטרה צפונית" },
    { "name": "Corvus", "abbr": "CRV", "ra": 186.6, "dec": -18.4, "name_he": "עורב" },
    { "name": "Crater", "abbr": "CRT", "ra": 169.5, "dec": -16.3, "name_he": "גביע" },
    { "name": "Crux", "abbr": "CRU", "ra": 186.7, "dec": -60.2, "name_he": "צלב הדרום" },
    { "name": "Cygnus", "abbr": "CYG", "ra": 308.8, "dec": 44.5, "name_he": "ברבור" },
    { "name": "Delphinus", "abbr": "DEL", "ra": 310.4, "dec": 11.7, "name_he": "דולפין" },
    { "name": "Dorado", "abbr": "DOR", "ra": 78.5, "dec": -59.4, "name_he": "דג זהב" },
    { "name": "Draco", "abbr": "DRA", "ra": 255.6, "dec": 67.8, "name_he": "דרקון" },
    { "name": "Equuleus", "abbr": "EQU", "ra": 319.2, "dec": 7.8, "name_he": "סייח" },
    { "name": "Eridanus", "abbr": "ERI", "ra": 54.5, "dec": -29.9, "name_he": "ארידנוס" },
    { "name": "Fornax", "abbr": "FOR", "ra": 41.9, "dec": -31.6, "name_he": "תנור" },
    { "name": "Gemini", "abbr": "GEM", "ra": 106.0, "dec": 22.6, "name_he": "תאומים" },
    { "name": "Grus", "abbr": "GRU", "ra": 336.8, "dec": -46.4, "name_he": "עגור" },
    { "name": "Hercules", "abbr": "HER", "ra": 251.4, "dec": 27.5, "name_he": "הרקולס" },
    { "name": "Horologium", "abbr": "HOR", "ra": 49.3, "dec": -53.3, "name_he": "שעון" },
    { "name": "Hydra", "abbr": "HYA", "ra": 142.1, "dec": -14.5, "name_he": "נחש מים" },
    { "name": "Hydrus", "abbr": "HYI", "ra": 35.1, "dec": -70.0, "name_he": "נחש מים קטן" },
    { "name": "Indus", "abbr": "IND", "ra": 317.3, "dec": -59.7, "name_he": "אינדיאני" },
    { "name": "Lacerta", "abbr": "LAC", "ra": 336.8, "dec": 46.0, "name_he": "לטאה" },
    { "name": "Leo", "abbr": "LEO", "ra": 160.0, "dec": 13.1, "name_he": "אריה" },
    { "name": "Leo Minor", "abbr": "LMI", "ra": 153.7, "dec": 32.8, "name_he": "אריה קטן" },
    { "name": "Lepus", "abbr": "LEP", "ra": 83.5, "dec": -19.0, "name_he": "ארנבת" },
    { "name": "Libra", "abbr": "LIB", "ra": 228.0, "dec": -15.2, "name_he": "מאזניים" },
    { "name": "Lupus", "abbr": "LUP", "ra": 229.4, "dec": -42.7, "name_he": "זאב" },
    { "name": "Lynx", "abbr": "LYN", "ra": 119.9, "dec": 47.5, "name_he": "שונר" },
    { "name": "Lyra", "abbr": "LYR", "ra": 281.8, "dec": 36.7, "name_he": "נבל" },
    { "name": "Mensa", "abbr": "MEN", "ra": 78.8, "dec": -77.5, "name_he": "שולחן" },
    { "name": "Microscopium", "abbr": "MIC", "ra": 314.5, "dec": -36.3, "name_he": "מיקרוסקופ" },
    { "name": "Monoceros", "abbr": "MON", "ra": 105.9, "dec": -5.4, "name_he": "חד-קרן" },
    { "name": "Musca", "abbr": "MUS", "ra": 186.8, "dec": -70.2, "name_he": "זבוב" },
    { "name": "Norma", "abbr": "NOR", "ra": 239.9, "dec": -51.3, "name_he": "סרגל" },
    { "name": "Octans", "abbr": "OCT", "ra": 345.0, "dec": -82.1, "name_he": "שמינית" },
    { "name": "Ophiuchus", "abbr": "OPH", "ra": 259.0, "dec": -7.9, "name_he": "נושא הנחש" },
    { "name": "Orion", "abbr": "ORI", "ra": 83.6, "dec": 5.9, "name_he": "אוריון (צייד)" },
    { "name": "Pavo", "abbr": "PAV", "ra": 294.2, "dec": -65.8, "name_he": "טווס" },
    { "name": "Pegasus", "abbr": "PEG", "ra": 341.6, "dec": 19.5, "name_he": "פגסוס" },
    { "name": "Perseus", "abbr": "PER", "ra": 47.6, "dec": 45.4, "name_he": "פרסאוס" },
    { "name": "Phoenix", "abbr": "PHE", "ra": 13.7, "dec": -48.9, "name_he": "עוף החול" },
    { "name": "Pictor", "abbr": "PIC", "ra": 85.6, "dec": -53.4, "name_he": "כן ציור" },
    { "name": "Pisces", "abbr": "PSC", "ra": 13.5, "dec": 13.7, "name_he": "דגים" },
    { "name": "Piscis Austrinus", "abbr": "PSA", "ra": 334.3, "dec": -30.6, "name_he": "דג דרומי" },
    { "name": "Puppis", "abbr": "PUP", "ra": 113.9, "dec": -31.2, "name_he": "ירכתי הספינה" },
    { "name": "Pyxis", "abbr": "PYX", "ra": 134.3, "dec": -30.1, "name_he": "מצפן" },
    { "name": "Reticulum", "abbr": "RET", "ra": 58.9, "dec": -60.0, "name_he": "רשת" },
    { "name": "Sagitta", "abbr": "SGE", "ra": 297.3, "dec": 18.8, "name_he": "חץ" },
    { "name": "Sagittarius", "abbr": "SGR", "ra": 286.5, "dec": -28.5, "name_he": "קשת" },
    { "name": "Scorpius", "abbr": "SCO", "ra": 253.5, "dec": -31.1, "name_he": "עקרב" },
    { "name": "Sculptor", "abbr": "SCL", "ra": 0.4, "dec": -32.1, "name_he": "פסל" },
    { "name": "Scutum", "abbr": "SCT", "ra": 280.0, "dec": -9.9, "name_he": "מגן" },
    { "name": "Serpens", "abbr": "SER", "ra": 239.2, "dec": 4.5, "name_he": "נחש" },
    { "name": "Sextans", "abbr": "SEX", "ra": 154.0, "dec": -2.6, "name_he": "סקסטנט" },
    { "name": "Taurus", "abbr": "TAU", "ra": 69.3, "dec": 14.8, "name_he": "שור" },
    { "name": "Telescopium", "abbr": "TEL", "ra": 288.7, "dec": -51.0, "name_he": "טלסקופ" },
    { "name": "Triangulum", "abbr": "TRI", "ra": 33.8, "dec": 31.5, "name_he": "משולש" },
    { "name": "Triangulum Australe", "abbr": "TRA", "ra": 241.1, "dec": -65.4, "name_he": "משולש דרומי" },
    { "name": "Tucana", "abbr": "TUC", "ra": 356.5, "dec": -65.8, "name_he": "טוקן" },
    { "name": "Ursa Major", "abbr": "UMA", "ra": 171.7, "dec": 50.7, "name_he": "הדובה הגדולה" },
    { "name": "Ursa Minor", "abbr": "UMI", "ra": 225.0, "dec": 77.5, "name_he": "הדובה הקטנה" },
    { "name": "Vela", "abbr": "VEL", "ra": 140.0, "dec": -47.2, "name_he": "מפרש" },
    { "name": "Virgo", "abbr": "VIR", "ra": 198.5, "dec": -4.2, "name_he": "בתולה" },
    { "name": "Volans", "abbr": "VOL", "ra": 116.8, "dec": -69.8, "name_he": "דג דואה" },
    { "name": "Vulpecula", "abbr": "VUL", "ra": 303.4, "dec": 24.4, "name_he": "שועלון" }
];
