const GLOSSARY_ITEMS = [
    {
        title: "The Exposure Triangle in Astrophotography",
        category: "Basic Concepts",
        content: `
            <p>Unlike daytime photography, astrophotography relies heavily on extremely long exposure times instead of fast shutter speeds. The traditional exposure triangle (ISO, Aperture, Shutter Speed) is adapted here:</p>
            <ul>
                <li><strong>Exposure Time (Shutter Speed):</strong> Usually measured in minutes (e.g., 300 seconds). Longer exposures capture more faint detail but require extremely precise tracking.</li>
                <li><strong>Gain / ISO:</strong> Determines the sensor's sensitivity to light. Higher gain increases brightness but also increases noise. Astrophotographers usually find a "sweet spot" for their specific camera (e.g., Gain 100 on the ZWO ASI2600).</li>
                <li><strong>Focal Ratio (Aperture):</strong> The speed of the optical system. A lower f-number (e.g., f/4) is "faster" and gathers light more quickly than a higher f-number (e.g., f/10).</li>
            </ul>
        `
    },
    {
        title: "Signal-to-Noise Ratio (SNR)",
        category: "Basic Concepts",
        content: `
            <p>SNR is arguably the most important metric in astrophotography. The goal of imaging for multiple hours is to increase the amount of "Signal" (the real light from the galaxy or nebula) while mathematically canceling out the random "Noise" generated by the camera sensor or light pollution.</p>
            <p>Stacking 100 images together doesn't make the image 100 times brighter; it makes the random noise disappear, leaving behind a smooth, clean signal that can be stretched in processing.</p>
        `
    },
    {
        title: "Calibration Frames (Darks, Flats, Biases)",
        category: "Basic Concepts",
        content: `
            <p>Calibration frames are taken specifically to mathematically remove imperfections from your 'Light' frames (your actual pictures of space).</p>
            <ul>
                <li><strong>Darks:</strong> Taken with the lens cap on at the same temperature, gain, and exposure time as your light frames. Removes "hot pixels" and thermal sensor noise.</li>
                <li><strong>Flats:</strong> Photos of an evenly illuminated surface (like a tracing panel or twilight sky). Used to remove dust motes on your sensor/filters and correct for vignetting (dark corners).</li>
                <li><strong>Biases/Dark Flats:</strong> Extremely short exposures (or matching flat exposures) taken with the cap on to remove the baseline read noise of the camera electronics.</li>
            </ul>
        `
    },
    {
        title: "Plate Solving",
        category: "Terminology",
        content: `
            <p>A software process where the computer takes a test photo of the sky, analyzes the star patterns in the image, and compares it to a database to figure out *exactly* where the telescope is pointing coordinates-wise. This completely eliminates the need for manual star alignment.</p>
        `
    },
    {
        title: "Dithering",
        category: "Terminology",
        content: `
            <p>Moving the telescope mount by a few random pixels between every single exposure. When the images are stacked later, the alignment software shifts the pictures back into place, which causes random sensor noise (like fixed pattern noise) to smear out and disappear. Dithering is essential for clean images!</p>
        `
    },
    {
        title: "Backfocus",
        category: "Terminology",
        content: `
            <p>The exact required distance (measured in millimeters) between the back element of your telescope (usually a flattener or reducer) and the camera sensor. If this measurement is off by even 1mm, the stars in the corners of your image will look like stretched ovals or commas instead of pinpoints.</p>
        `
    },
    {
        title: "Meridian Flip",
        category: "Terminology",
        content: `
            <p>Because equatorial mounts follow the rotation of the Earth, the telescope will eventually hit the tripod as the target crosses the "meridian" (the imaginary line running North to South directly overhead). A Meridian Flip is a maneuver where the telescope swings 180 degrees to the other side of the mount to continue tracking the object as it sets.</p>
        `
    },
    {
        title: "Equatorial (EQ) vs Alt-Azimuth (Alt-Az) Mounts",
        category: "Equipment",
        content: `
            <p><strong>Alt-Az Mounts:</strong> Move Up/Down and Left/Right. Great for visual astronomy, but terrible for astrophotography because the sky rotates across the field of view (field rotation), limiting exposures to a few seconds.</p>
            <p><strong>EQ Mounts:</strong> One axis is aligned directly with the North Celestial Pole (Polaris). This allows the mount to perfectly track the smooth rotation of the stars across the sky, enabling exposures lasting 10+ minutes.</p>
        `
    },
    {
        title: "Monochrome vs Color (OSC) Cameras",
        category: "Equipment",
        content: `
            <p><strong>One Shot Color (OSC):</strong> Similar to a DSLR. A microlens matrix over the sensor automatically shoots Red, Green, and Blue at the same time. Easier to use, but less sensitive and harder to shoot narrowband effectively.</p>
            <p><strong>Monochrome:</strong> A black-and-white sensor. Shoots one color channel at a time using physical glass filters (Luminance, Red, Green, Blue, Hydrogen, Oxygen, Sulfur) slotted in front of the chip on a motorized wheel. Highly sensitive, sharpest data, but extremely time-consuming.</p>
        `
    }
];
