const GLOSSARY_ITEMS = [
    {
        title: "The Exposure Triangle in Astrophotography",
        category: "Basic Concepts",
        content: `
            <p>Unlike daytime photography, astrophotography relies heavily on extremely long exposure times instead of fast shutter speeds. The traditional exposure triangle (ISO, Aperture, Shutter Speed) is adapted here:</p>
            <ul>
                <li><strong>Exposure Time (Shutter Speed):</strong> Usually measured in minutes (e.g., 300 seconds). Longer exposures capture more faint detail but require extremely precise tracking.</li>
                <li><strong>Gain / ISO:</strong> Determines the sensor's sensitivity to light. Higher gain increases brightness but also increases noise. Astrophotographers usually find a "sweet spot" for their specific camera (e.g., Gain 100 on the ZWO ASI2600).</li>
                <li><strong>Focal Ratio (Aperture):</strong> The speed of the optical system. A lower f-number (e.g., f/4) is "faster" and gathers light more quickly than a higher f-number (e.g., f/10).</li>
            </ul>
        `
    },
    {
        title: "Signal-to-Noise Ratio (SNR)",
        category: "Basic Concepts",
        content: `
            <p>SNR is arguably the most important metric in astrophotography. The goal of imaging for multiple hours is to increase the amount of "Signal" (the real light from the galaxy or nebula) while mathematically canceling out the random "Noise" generated by the camera sensor or light pollution.</p>
            <p>Stacking 100 images together doesn't make the image 100 times brighter; it makes the random noise disappear, leaving behind a smooth, clean signal that can be stretched in processing.</p>
        `
    },
    {
        title: "Calibration Frames (Darks, Flats, Biases)",
        category: "Basic Concepts",
        content: `
            <p>Calibration frames are taken specifically to mathematically remove imperfections from your 'Light' frames (your actual pictures of space).</p>
            <ul>
                <li><strong>Darks:</strong> Taken with the lens cap on at the same temperature, gain, and exposure time as your light frames. Removes "hot pixels" and thermal sensor noise.</li>
                <li><strong>Flats:</strong> Photos of an evenly illuminated surface (like a tracing panel or twilight sky). Used to remove dust motes on your sensor/filters and correct for vignetting (dark corners).</li>
                <li><strong>Biases/Dark Flats:</strong> Extremely short exposures (or matching flat exposures) taken with the cap on to remove the baseline read noise of the camera electronics.</li>
            </ul>
        `
    },
    {
        title: "Plate Solving",
        category: "Terminology",
        content: `
            <p>A software process where the computer takes a test photo of the sky, analyzes the star patterns in the image, and compares it to a database to figure out *exactly* where the telescope is pointing coordinates-wise. This completely eliminates the need for manual star alignment.</p>
        `
    },
    {
        title: "Dithering",
        category: "Terminology",
        content: `
            <p>Moving the telescope mount by a few random pixels between every single exposure. When the images are stacked later, the alignment software shifts the pictures back into place, which causes random sensor noise (like fixed pattern noise) to smear out and disappear. Dithering is essential for clean images!</p>
        `
    },
    {
        title: "Backfocus",
        category: "Terminology",
        content: `
            <p>The exact required distance (measured in millimeters) between the back element of your telescope (usually a flattener or reducer) and the camera sensor. If this measurement is off by even 1mm, the stars in the corners of your image will look like stretched ovals or commas instead of pinpoints.</p>
        `
    },
    {
        title: "Meridian Flip",
        category: "Terminology",
        content: `
            <p>Because equatorial mounts follow the rotation of the Earth, the telescope will eventually hit the tripod as the target crosses the "meridian" (the imaginary line running North to South directly overhead). A Meridian Flip is a maneuver where the telescope swings 180 degrees to the other side of the mount to continue tracking the object as it sets.</p>
        `
    },
    {
        title: "Equatorial (EQ) vs Alt-Azimuth (Alt-Az) Mounts",
        category: "Equipment",
        content: `
            <p><strong>Alt-Az Mounts:</strong> Move Up/Down and Left/Right. Great for visual astronomy, but terrible for astrophotography because the sky rotates across the field of view (field rotation), limiting exposures to a few seconds.</p>
            <p><strong>EQ Mounts:</strong> One axis is aligned directly with the North Celestial Pole (Polaris). This allows the mount to perfectly track the smooth rotation of the stars across the sky, enabling exposures lasting 10+ minutes.</p>
        `
    },
    {
        title: "Monochrome vs Color (OSC) Cameras",
        category: "Equipment",
        content: `
            <p><strong>One Shot Color (OSC):</strong> Similar to a DSLR. A microlens matrix over the sensor automatically shoots Red, Green, and Blue at the same time. Easier to use, but less sensitive and harder to shoot narrowband effectively.</p>
            <p><strong>Monochrome:</strong> A black-and-white sensor. Shoots one color channel at a time using physical glass filters (Luminance, Red, Green, Blue, Hydrogen, Oxygen, Sulfur) slotted in front of the chip on a motorized wheel. Highly sensitive, sharpest data, but extremely time-consuming.</p>
        `
    },
    {
        title: "Apochromatic Refractor (APO)",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> A telescope that uses specialized extra-low dispersion (ED) glass to bring three wavelengths (Red, Green, Blue) to the same focal point.</p>
            <p><strong>Example:</strong> When shooting a bright star like Sirius, an APO telescope prevents the "purple halo" (chromatic aberration) that cheaper achromatic telescopes produce.</p>
        `
    },
    {
        title: "Backfocal Distance (Backfocus)",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> The exact distance from the rear thread of a corrector/reducer to the camera sensor.</p>
            <p><strong>Example:</strong> Your William Optics FLT132 flattener might require exactly 55mm. If you are at 53mm, the stars in the corners of your Andromeda Galaxy shot will appear elongated or "stretched" toward the center.</p>
        `
    },
    {
        title: "Harmonic Drive Mount",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> A mount using strain-wave gears that provide massive torque without the need for bulky counterweights.</p>
            <p><strong>Example:</strong> Using a ZWO AM5 to carry a 10kg payload without needing a 5kg metal weight, making it the "ultimate" portable setup for dark-sky trips.</p>
        `
    },
    {
        title: "Plate Solving",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> Software that "reads" the stars in a photo and calculates the exact coordinates the telescope is pointing at.</p>
            <p><strong>Example:</strong> You tell the mount to go to the Tadpole Nebula. It slews nearby; the software takes a 2-second exposure, realizes it's 50 pixels off, and automatically centers the target perfectly.</p>
        `
    },
    {
        title: "Off-Axis Guider (OAG)",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> A device that uses a small prism to "steal" a bit of light from the main telescope to feed a guide camera.</p>
            <p><strong>Example:</strong> Essential for long focal lengths (like an SCT). It eliminates "differential flexure" because the guide camera "sees" exactly what the main camera sees.</p>
        `
    },
    {
        title: "Quantum Efficiency (QE)",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> The percentage of photons hitting the sensor that are actually converted into an electrical signal.</p>
            <p><strong>Example:</strong> A camera with 80% QE (like the ASI2600MM) captures nearly twice as much light in the same time as an older DSLR with 40% QE.</p>
        `
    },
    {
        title: "Signal-to-Noise Ratio (SNR)",
        category: "Processing & Data Analysis",
        content: `
            <p><strong>Definition:</strong> The ratio of real celestial light to the random electronic and thermal noise of the camera.</p>
            <p><strong>Example:</strong> A 5-minute exposure of the Hercules Galaxy Cluster looks "noisy." By stacking 50 of those frames (4 hours total), the SNR increases by the square root of the number of frames, making the faint tidal tails visible.</p>
        `
    },
    {
        title: "Dithering",
        category: "Processing & Data Analysis",
        content: `
            <p><strong>Definition:</strong> Shifting the telescope slightly (1-10 pixels) in a random direction between every few frames.</p>
            <p><strong>Example:</strong> If your sensor has a "hot pixel" in the middle, dithering moves it around. During stacking, the software sees that pixel moving while the stars stay still, allowing it to "reject" the noise entirely.</p>
        `
    },
    {
        title: "Linear vs. Non-Linear",
        category: "Processing & Data Analysis",
        content: `
            <p><strong>Definition:</strong> Linear data is the raw, dark output where pixel values match the light count. Non-Linear is data that has been "stretched" to be visible.</p>
            <p><strong>Example:</strong> You must perform Deconvolution while the image is Linear (dark) to accurately sharpen the stars before you "stretch" the image to show the nebula.</p>
        `
    },
    {
        title: "Bayer Matrix (Debayering)",
        category: "Processing & Data Analysis",
        content: `
            <p><strong>Definition:</strong> The grid of Red, Green, and Blue filters over a color sensor.</p>
            <p><strong>Example:</strong> A raw file from a One-Shot Color (OSC) camera looks like a gray checkerboard. The software must "Debayer" it to interpret which pixel is which color to create a final color image.</p>
        `
    },
    {
        title: "Hydrogen-Alpha (Hα)",
        category: "Narrowband & Filters",
        content: `
            <p><strong>Definition:</strong> A narrowband filter that only allows light from ionized hydrogen (656.3nm) to pass.</p>
            <p><strong>Example:</strong> Even under a full moon or heavy light pollution, an Hα filter allows you to capture the deep red structures of the California Nebula with high contrast.</p>
        `
    },
    {
        title: "Oxygen-III (OIII)",
        category: "Narrowband & Filters",
        content: `
            <p><strong>Definition:</strong> A filter for doubly-ionized oxygen (500.7nm), typically appearing teal or blue-green.</p>
            <p><strong>Example:</strong> In a Planetary Nebula like the Dumbbell (M27), the OIII filter captures the "outer shell" that is often invisible in standard RGB shots.</p>
        `
    },
    {
        title: "Hubble Palette (SHO)",
        category: "Narrowband & Filters",
        content: `
            <p><strong>Definition:</strong> A false-color mapping where Sulfur-II is Red, Hydrogen-Alpha is Green, and Oxygen-III is Blue.</p>
            <p><strong>Example:</strong> This is how the famous "Pillars of Creation" were processed. It allows us to see exactly where different gases are located in a nebula like The Rosette.</p>
        `
    },
    {
        title: "The Bortle Scale",
        category: "Atmospheric & Environment",
        content: `
            <p><strong>Definition:</strong> A 1-9 scale of sky darkness.</p>
            <p><strong>Example:</strong> On your site, you might note: "Captured at a Bortle 3 site." This tells the viewer the sky was dark enough to see the Milky Way clearly with the naked eye.</p>
        `
    },
    {
        title: "Astronomical Seeing",
        category: "Atmospheric & Environment",
        content: `
            <p><strong>Definition:</strong> A measurement of atmospheric turbulence.</p>
            <p><strong>Example:</strong> On a night of "Poor Seeing," your stars will look like fuzzy blobs regardless of how perfect your focus is, because the air is "boiling."</p>
        `
    }
];
