const GLOSSARY_ITEMS = [
    {
        title: "The Exposure Triangle in Astrophotography",
        category: "Basic Concepts",
        content: `
            <p>Unlike daytime photography, astrophotography relies heavily on extremely long exposure times instead of fast shutter speeds. The traditional exposure triangle (ISO, Aperture, Shutter Speed) is adapted here:</p>
            <ul>
                <li><strong>Exposure Time (Shutter Speed):</strong> Usually measured in minutes (e.g., 300 seconds). Longer exposures capture more faint detail but require extremely precise tracking.</li>
                <li><strong>Gain / ISO:</strong> Determines the sensor's sensitivity to light. Higher gain increases brightness but also increases noise. Astrophotographers usually find a "sweet spot" for their specific camera (e.g., Gain 100 on the ZWO ASI2600).</li>
                <li><strong>Focal Ratio (Aperture):</strong> The speed of the optical system. A lower f-number (e.g., f/4) is "faster" and gathers light more quickly than a higher f-number (e.g., f/10).</li>
            </ul>
        `
    },
    {
        title: "Signal-to-Noise Ratio (SNR)",
        category: "Basic Concepts",
        content: `
            <p>SNR is arguably the most important metric in astrophotography. The goal of imaging for multiple hours is to increase the amount of "Signal" (the real light from the galaxy or nebula) while mathematically canceling out the random "Noise" generated by the camera sensor or light pollution.</p>
            <p>Stacking 100 images together doesn't make the image 100 times brighter; it makes the random noise disappear, leaving behind a smooth, clean signal that can be stretched in processing.</p>
        `
    },
    {
        title: "Calibration Frames (Darks, Flats, Biases)",
        category: "Basic Concepts",
        content: `
            <p>Calibration frames are taken specifically to mathematically remove imperfections from your 'Light' frames (your actual pictures of space).</p>
            <ul>
                <li><strong>Darks:</strong> Taken with the lens cap on at the same temperature, gain, and exposure time as your light frames. Removes "hot pixels" and thermal sensor noise.</li>
                <li><strong>Flats:</strong> Photos of an evenly illuminated surface (like a tracing panel or twilight sky). Used to remove dust motes on your sensor/filters and correct for vignetting (dark corners).</li>
                <li><strong>Biases/Dark Flats:</strong> Extremely short exposures (or matching flat exposures) taken with the cap on to remove the baseline read noise of the camera electronics.</li>
            </ul>
        `
    },
    {
        title: "Plate Solving",
        category: "Terminology",
        content: `
            <p>A software process where the computer takes a test photo of the sky, analyzes the star patterns in the image, and compares it to a database to figure out *exactly* where the telescope is pointing coordinates-wise. This completely eliminates the need for manual star alignment.</p>
        `
    },
    {
        title: "Dithering",
        category: "Terminology",
        content: `
            <p>Moving the telescope mount by a few random pixels between every single exposure. When the images are stacked later, the alignment software shifts the pictures back into place, which causes random sensor noise (like fixed pattern noise) to smear out and disappear. Dithering is essential for clean images!</p>
        `
    },
    {
        title: "Backfocus",
        category: "Terminology",
        content: `
            <p>The exact required distance (measured in millimeters) between the back element of your telescope (usually a flattener or reducer) and the camera sensor. If this measurement is off by even 1mm, the stars in the corners of your image will look like stretched ovals or commas instead of pinpoints.</p>
        `
    },
    {
        title: "Meridian Flip",
        category: "Terminology",
        content: `
            <p>Because equatorial mounts follow the rotation of the Earth, the telescope will eventually hit the tripod as the target crosses the "meridian" (the imaginary line running North to South directly overhead). A Meridian Flip is a maneuver where the telescope swings 180 degrees to the other side of the mount to continue tracking the object as it sets.</p>
        `
    },
    {
        title: "Equatorial (EQ) vs Alt-Azimuth (Alt-Az) Mounts",
        category: "Equipment",
        content: `
            <p><strong>Alt-Az Mounts:</strong> Move Up/Down and Left/Right. Great for visual astronomy, but terrible for astrophotography because the sky rotates across the field of view (field rotation), limiting exposures to a few seconds.</p>
            <p><strong>EQ Mounts:</strong> One axis is aligned directly with the North Celestial Pole (Polaris). This allows the mount to perfectly track the smooth rotation of the stars across the sky, enabling exposures lasting 10+ minutes.</p>
        `
    },
    {
        title: "Monochrome vs Color (OSC) Cameras",
        category: "Equipment",
        content: `
            <p><strong>One Shot Color (OSC):</strong> Similar to a DSLR. A microlens matrix over the sensor automatically shoots Red, Green, and Blue at the same time. Easier to use, but less sensitive and harder to shoot narrowband effectively.</p>
            <p><strong>Monochrome:</strong> A black-and-white sensor. Shoots one color channel at a time using physical glass filters (Luminance, Red, Green, Blue, Hydrogen, Oxygen, Sulfur) slotted in front of the chip on a motorized wheel. Highly sensitive, sharpest data, but extremely time-consuming.</p>
        `
    },
    {
        title: "Apochromatic Refractor (APO)",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> A telescope that uses specialized extra-low dispersion (ED) glass to bring three wavelengths (Red, Green, Blue) to the same focal point.</p>
            <p><strong>Example:</strong> When shooting a bright star like Sirius, an APO telescope prevents the "purple halo" (chromatic aberration) that cheaper achromatic telescopes produce.</p>
        `
    },
    {
        title: "Backfocal Distance (Backfocus)",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> The exact distance from the rear thread of a corrector/reducer to the camera sensor.</p>
            <p><strong>Example:</strong> Your William Optics FLT132 flattener might require exactly 55mm. If you are at 53mm, the stars in the corners of your Andromeda Galaxy shot will appear elongated or "stretched" toward the center.</p>
        `
    },
    {
        title: "Harmonic Drive Mount",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> A mount using strain-wave gears that provide massive torque without the need for bulky counterweights.</p>
            <p><strong>Example:</strong> Using a ZWO AM5 to carry a 10kg payload without needing a 5kg metal weight, making it the "ultimate" portable setup for dark-sky trips.</p>
        `
    },
    {
        title: "Plate Solving",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> Software that "reads" the stars in a photo and calculates the exact coordinates the telescope is pointing at.</p>
            <p><strong>Example:</strong> You tell the mount to go to the Tadpole Nebula. It slews nearby; the software takes a 2-second exposure, realizes it's 50 pixels off, and automatically centers the target perfectly.</p>
        `
    },
    {
        title: "Off-Axis Guider (OAG)",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> A device that uses a small prism to "steal" a bit of light from the main telescope to feed a guide camera.</p>
            <p><strong>Example:</strong> Essential for long focal lengths (like an SCT). It eliminates "differential flexure" because the guide camera "sees" exactly what the main camera sees.</p>
        `
    },
    {
        title: "Quantum Efficiency (QE)",
        category: "Hardware & Optics",
        content: `
            <p><strong>Definition:</strong> The percentage of photons hitting the sensor that are actually converted into an electrical signal.</p>
            <p><strong>Example:</strong> A camera with 80% QE (like the ASI2600MM) captures nearly twice as much light in the same time as an older DSLR with 40% QE.</p>
        `
    },
    {
        title: "Signal-to-Noise Ratio (SNR)",
        category: "Processing & Data Analysis",
        content: `
            <p><strong>Definition:</strong> The ratio of real celestial light to the random electronic and thermal noise of the camera.</p>
            <p><strong>Example:</strong> A 5-minute exposure of the Hercules Galaxy Cluster looks "noisy." By stacking 50 of those frames (4 hours total), the SNR increases by the square root of the number of frames, making the faint tidal tails visible.</p>
        `
    },
    {
        title: "Dithering",
        category: "Processing & Data Analysis",
        content: `
            <p><strong>Definition:</strong> Shifting the telescope slightly (1-10 pixels) in a random direction between every few frames.</p>
            <p><strong>Example:</strong> If your sensor has a "hot pixel" in the middle, dithering moves it around. During stacking, the software sees that pixel moving while the stars stay still, allowing it to "reject" the noise entirely.</p>
        `
    },
    {
        title: "Linear vs. Non-Linear",
        category: "Processing & Data Analysis",
        content: `
            <p><strong>Definition:</strong> Linear data is the raw, dark output where pixel values match the light count. Non-Linear is data that has been "stretched" to be visible.</p>
            <p><strong>Example:</strong> You must perform Deconvolution while the image is Linear (dark) to accurately sharpen the stars before you "stretch" the image to show the nebula.</p>
        `
    },
    {
        title: "Bayer Matrix (Debayering)",
        category: "Processing & Data Analysis",
        content: `
            <p><strong>Definition:</strong> The grid of Red, Green, and Blue filters over a color sensor.</p>
            <p><strong>Example:</strong> A raw file from a One-Shot Color (OSC) camera looks like a gray checkerboard. The software must "Debayer" it to interpret which pixel is which color to create a final color image.</p>
        `
    },
    {
        title: "Hydrogen-Alpha (Hα)",
        category: "Narrowband & Filters",
        content: `
            <p><strong>Definition:</strong> A narrowband filter that only allows light from ionized hydrogen (656.3nm) to pass.</p>
            <p><strong>Example:</strong> Even under a full moon or heavy light pollution, an Hα filter allows you to capture the deep red structures of the California Nebula with high contrast.</p>
        `
    },
    {
        title: "Oxygen-III (OIII)",
        category: "Narrowband & Filters",
        content: `
            <p><strong>Definition:</strong> A filter for doubly-ionized oxygen (500.7nm), typically appearing teal or blue-green.</p>
            <p><strong>Example:</strong> In a Planetary Nebula like the Dumbbell (M27), the OIII filter captures the "outer shell" that is often invisible in standard RGB shots.</p>
        `
    },
    {
        title: "Hubble Palette (SHO)",
        category: "Narrowband & Filters",
        content: `
            <p><strong>Definition:</strong> A false-color mapping where Sulfur-II is Red, Hydrogen-Alpha is Green, and Oxygen-III is Blue.</p>
            <p><strong>Example:</strong> This is how the famous "Pillars of Creation" were processed. It allows us to see exactly where different gases are located in a nebula like The Rosette.</p>
        `
    },
    {
        title: "The Bortle Scale",
        category: "Atmospheric & Environment",
        content: `
            <p><strong>Definition:</strong> A 1-9 scale of sky darkness.</p>
            <p><strong>Example:</strong> On your site, you might note: "Captured at a Bortle 3 site." This tells the viewer the sky was dark enough to see the Milky Way clearly with the naked eye.</p>
        `
    },
    {
        title: "Astronomical Seeing",
        category: "Atmospheric & Environment",
        content: `
            <p><strong>Definition:</strong> A measurement of atmospheric turbulence.</p>
            <p><strong>Example:</strong> On a night of "Poor Seeing," your stars will look like fuzzy blobs regardless of how perfect your focus is, because the air is "boiling."</p>
        `
    },
    {
        title: "Bias Frame",
        category: "Calibration & Data Integrity",
        content: `
            <p><strong>Definition:</strong> A zero-length exposure (fastest shutter speed) taken with the lens cap on. It records the inherent electronic "read noise" of the camera sensor.</p>
            <p><strong>Example:</strong> By subtracting a Master Bias from your light frames, you remove the base-level electronic hum that would otherwise create a "fog" over your faint nebula details.</p>
        `
    },
    {
        title: "Dark Frame",
        category: "Calibration & Data Integrity",
        content: `
            <p><strong>Definition:</strong> An exposure of the exact same length, temperature, and gain as your light frame, but with the optics covered. It captures thermal noise and "hot pixels."</p>
            <p><strong>Example:</strong> If your 300-second shot of the Tadpole Nebula has 50 bright red dots (hot pixels), subtracting a Master Dark identifies those specific pixels and removes them.</p>
        `
    },
    {
        title: "Flat Frame",
        category: "Calibration & Data Integrity",
        content: `
            <p><strong>Definition:</strong> An image of a perfectly even, neutral light source taken through the entire optical train. It maps out vignetting (dark corners) and dust motes on the sensor.</p>
            <p><strong>Example:</strong> If there is a "dust donut" on your telescope's glass, a Flat Frame creates a map of that shadow. During processing, the software "divides" the light frame by the flat, making the dust disappear.</p>
        `
    },
    {
        title: "Dark-Flat Frame",
        category: "Calibration & Data Integrity",
        content: `
            <p><strong>Definition:</strong> A dark frame specifically for the flat frames. It is an exposure of the same length as the flat, but with no light, used to calibrate the flats themselves.</p>
            <p><strong>Example:</strong> Used primarily with CMOS cameras (like the ASI2600) that don't scale bias frames well; this ensures your flats are perfectly clean before they touch your light data.</p>
        `
    },
    {
        title: "Master Frame",
        category: "Calibration & Data Integrity",
        content: `
            <p><strong>Definition:</strong> The resulting file created by stacking dozens of individual calibration frames (e.g., 50 Darks become one "Master Dark").</p>
            <p><strong>Example:</strong> A single dark frame is noisy; a Master Dark is a smooth, high-SNR mathematical average of the sensor's thermal behavior.</p>
        `
    },
    {
        title: "Sub-frame Weighting",
        category: "Advanced Stacking",
        content: `
            <p><strong>Definition:</strong> An algorithm that analyzes every individual image and gives a "score" based on star roundness, SNR, and sky overhead (transparency).</p>
            <p><strong>Example:</strong> If a thin cloud passed by during your 10th shot of M31, the software gives it a lower "weight" so it doesn't degrade the final stack as much as the clear shots.</p>
        `
    },
    {
        title: "Pixel Rejection (Sigma Clipping)",
        category: "Advanced Stacking",
        content: `
            <p><strong>Definition:</strong> A statistical method that looks at a stack of images and throws away pixels that don't match the others (outliers).</p>
            <p><strong>Example:</strong> If a satellite or a plane flies through one frame of your Hercules Cluster, Sigma Clipping sees that the "streak" is only in one frame and deletes it during the stacking process.</p>
        `
    },
    {
        title: "Registration (Alignment)",
        category: "Advanced Stacking",
        content: `
            <p><strong>Definition:</strong> The process of mathematically rotating and shifting every image in a set so that the stars overlap perfectly.</p>
            <p><strong>Example:</strong> Even if your mount tracked perfectly, the stars might shift by 1 pixel due to atmospheric refraction. Registration ensures the Leo Triplet stays razor-sharp across 100 frames.</p>
        `
    },
    {
        title: "Drizzle (Bayer Drizzle)",
        category: "Advanced Stacking",
        content: `
            <p><strong>Definition:</strong> A technique originally developed for the Hubble Space Telescope to recover resolution from under-sampled data by using dithered images to "fill in" the gaps between pixels.</p>
            <p><strong>Example:</strong> If you shoot a wide-field nebula with large pixels, your stars might look blocky. Using 2x Drizzle during stacking can make the stars rounder and recover finer details in the gas clouds.</p>
        `
    },
    {
        title: "Deconvolution",
        category: "Advanced Processing",
        content: `
            <p><strong>Definition:</strong> A mathematical algorithm that attempts to reverse the blurring effects caused by the atmosphere and telescope optics.</p>
            <p><strong>Example:</strong> By applying deconvolution to the core of the M13 Globular Cluster, you can "tighten" the stars, revealing individual points of light that were previously smeared together.</p>
        `
    },
    {
        title: "Star Reduction (Morphological Transformation)",
        category: "Advanced Processing",
        content: `
            <p><strong>Definition:</strong> Using masks and filters to shrink the size of stars in a final image without affecting the brightness of the nebula or galaxy.</p>
            <p><strong>Example:</strong> In a crowded area like the Sadr Region, the stars can overwhelm the nebula. Reducing them makes the faint hydrogen clouds "pop" and become the focus of the image.</p>
        `
    },
    {
        title: "SCNR (Subtractive Chromatic Noise Reduction)",
        category: "Advanced Processing",
        content: `
            <p><strong>Definition:</strong> A specialized tool used to remove unnatural green tints from an image, as there are almost no "green" objects in deep space.</p>
            <p><strong>Example:</strong> OSC cameras often produce a green cast due to the Bayer matrix having two green pixels for every one red/blue. SCNR "kills" the green, leaving a natural-looking background.</p>
        `
    },
    {
        title: "Local Histogram Equalization (LHE)",
        category: "Advanced Processing",
        content: `
            <p><strong>Definition:</strong> A tool that increases contrast in specific "local" areas of an image rather than stretching the whole thing.</p>
            <p><strong>Example:</strong> Used to bring out the "ripples" and "waves" inside the Orion Nebula without blowing out the bright stars or darkening the edges too much.</p>
        `
    },
    {
        title: "PixelMath",
        category: "Advanced Processing",
        content: `
            <p><strong>Definition:</strong> A powerful tool that allows you to use mathematical equations to combine, subtract, or modify images.</p>
            <p><strong>Example:</strong> You can use a formula like (Ha * 0.8) + (Red * 0.2) to blend narrowband data into a natural-looking RGB star field.</p>
        `
    },
    {
        title: "Dynamic Background Extraction (DBE)",
        category: "Advanced Processing",
        content: `
            <p><strong>Definition:</strong> Manually placing "sample points" on the background of an image to model and subtract complex light pollution or moon gradients.</p>
            <p><strong>Example:</strong> If your M81 image has a glow in the top-left from a neighbor's porch light, DBE maps that specific glow and subtracts it with surgical precision.</p>
        `
    },
    {
        title: "Right Ascension (RA)",
        category: "Celestial Coordinates & Navigation",
        content: `
            <p><strong>Definition:</strong> The celestial equivalent of longitude, measured in hours, minutes, and seconds eastward along the celestial equator.</p>
            <p><strong>Example:</strong> The Andromeda Galaxy (M31) is located at an RA of approximately 00h 42m. As the Earth rotates, this "coordinate" stays fixed relative to the stars, allowing your mount to find it any night it is above the horizon.</p>
        `
    },
    {
        title: "Declination (DEC)",
        category: "Celestial Coordinates & Navigation",
        content: `
            <p><strong>Definition:</strong> The celestial equivalent of latitude, measured in degrees north (+) or south (-) of the celestial equator.</p>
            <p><strong>Example:</strong> The North America Nebula has a DEC of +44°. Because this is a high positive number, it remains high in the sky for observers in the Northern Hemisphere (like Israel) for much of the year.</p>
        `
    },
    {
        title: "Meridian",
        category: "Celestial Coordinates & Navigation",
        content: `
            <p><strong>Definition:</strong> An imaginary line running from North to South, passing directly through the zenith (the highest point in the sky).</p>
            <p><strong>Example:</strong> When a target like the Tadpole Nebula "crosses the meridian," it is at its highest point in the sky, meaning you are shooting through the least amount of atmosphere for the sharpest possible data.</p>
        `
    },
    {
        title: "Meridian Flip",
        category: "Celestial Coordinates & Navigation",
        content: `
            <p><strong>Definition:</strong> The process where a German Equatorial Mount (GEM) must rotate 180 degrees to the other side of the pier as an object crosses the meridian to prevent the telescope from hitting the tripod legs.</p>
            <p><strong>Example:</strong> During a long session on M81, your software (like N.I.N.A. or ASIAIR) will automatically pause, flip the mount, re-center the target using plate solving, and resume guiding.</p>
        `
    },
    {
        title: "Celestial Equator",
        category: "Celestial Coordinates & Navigation",
        content: `
            <p><strong>Definition:</strong> The great circle on the imaginary celestial sphere, in the same plane as the Earth's equator.</p>
            <p><strong>Example:</strong> Objects located near the Celestial Equator (like the Orion Nebula) are visible from almost everywhere on Earth, both in the Northern and Southern hemispheres.</p>
        `
    },
    {
        title: "Emission Nebula",
        category: "Deep Sky Object (DSO) Classifications",
        content: `
            <p><strong>Definition:</strong> A cloud of ionized gas (mostly hydrogen) that emits light of various colors. The energy comes from high-energy photons emitted from a nearby hot star.</p>
            <p><strong>Example:</strong> The Rosette Nebula is a classic emission nebula. The young stars in the center ionize the surrounding hydrogen gas, causing it to glow brilliant red.</p>
        `
    },
    {
        title: "Reflection Nebula",
        category: "Deep Sky Object (DSO) Classifications",
        content: `
            <p><strong>Definition:</strong> A cloud of interstellar dust that reflects the light of a nearby star or stars. These typically appear blue because blue light is scattered more efficiently.</p>
            <p><strong>Example:</strong> The blue "haze" around the stars in the Pleiades (M45) is a reflection nebula. The dust isn't hot enough to glow on its own; it is simply reflecting the starlight.</p>
        `
    },
    {
        title: "Dark Nebula",
        category: "Deep Sky Object (DSO) Classifications",
        content: `
            <p><strong>Definition:</strong> A cloud of interstellar dust that is so dense it blocks the light from objects behind it, such as stars or brighter emission nebulae.</p>
            <p><strong>Example:</strong> The Horsehead Nebula is actually a dark nebula (Barnard 33) shaped like a chess piece, visible only because it sits in front of the bright red emission nebula IC 434.</p>
        `
    },
    {
        title: "Planetary Nebula",
        category: "Deep Sky Object (DSO) Classifications",
        content: `
            <p><strong>Definition:</strong> An expanding, glowing shell of ionized gas ejected from red giant stars late in their lives. They have nothing to do with actual planets.</p>
            <p><strong>Example:</strong> The Ring Nebula (M57) is a perfect example. It represents what our own Sun might look like in 5 billion years after it sheds its outer layers.</p>
        `
    },
    {
        title: "Supernova Remnant (SNR)",
        category: "Deep Sky Object (DSO) Classifications",
        content: `
            <p><strong>Definition:</strong> The structure resulting from the explosion of a star in a supernova. It consists of ejected material expanding at high speeds.</p>
            <p><strong>Example:</strong> The Veil Nebula in Cygnus is a massive SNR. The delicate "filaments" we photograph are the shockwaves of a star that exploded thousands of years ago, hitting the surrounding gas.</p>
        `
    },
    {
        title: "Airmass",
        category: "Technical Physics & Light",
        content: `
            <p><strong>Definition:</strong> A measure of the amount of atmosphere light must pass through to reach the telescope. Airmass is 1.0 at the zenith and increases as you look toward the horizon.</p>
            <p><strong>Example:</strong> Shooting a galaxy at 3.0 Airmass (low on the horizon) results in blurry, yellowed images because you are looking through three times more air than if it were directly overhead.</p>
        `
    },
    {
        title: "Atmospheric Dispersion",
        category: "Technical Physics & Light",
        content: `
            <p><strong>Definition:</strong> The "prism" effect of Earth's atmosphere that spreads starlight into a tiny spectrum (red on top, blue on bottom), especially when objects are low in the sky.</p>
            <p><strong>Example:</strong> When photographing Jupiter near the horizon, you might see a red fringe on one side and a blue fringe on the other. This is caused by dispersion, not your telescope.</p>
        `
    },
    {
        title: "Extinction",
        category: "Technical Physics & Light",
        content: `
            <p><strong>Definition:</strong> The loss of light from a celestial body as it passes through the atmosphere, caused by absorption or scattering by air molecules and dust.</p>
            <p><strong>Example:</strong> A star looks much dimmer at the horizon than at the zenith due to extinction. This is why we wait for targets to rise high before starting our "Luminance" exposures.</p>
        `
    },
    {
        title: "Integration Time (Total)",
        category: "Technical Physics & Light",
        content: `
            <p><strong>Definition:</strong> The sum of all individual exposures (subs) combined into a single final image.</p>
            <p><strong>Example:</strong> If you capture 60 frames at 300 seconds each, your Total Integration Time is 5 hours. More time directly translates to a higher Signal-to-Noise Ratio (SNR).</p>
        `
    },
    {
        title: "Opposition",
        category: "Solar System Dynamics & Planetary Terms",
        content: `
            <p><strong>Definition:</strong> The moment when a planet (like Mars or Jupiter) is on the opposite side of the Earth from the Sun. From our perspective, the planet is fully illuminated and at its closest point to Earth.</p>
            <p><strong>Example:</strong> During Mars Opposition, the planet appears much larger in your telescope, allowing you to capture fine surface details like the polar ice caps that are invisible at other times.</p>
        `
    },
    {
        title: "Conjunction",
        category: "Solar System Dynamics & Planetary Terms",
        content: `
            <p><strong>Definition:</strong> An event where two celestial objects (like two planets, or a planet and a star) appear very close to each other in the sky from our vantage point.</p>
            <p><strong>Example:</strong> The "Great Conjunction" of Jupiter and Saturn in 2020 allowed astrophotographers to capture both planets in a single high-magnification field of view.</p>
        `
    },
    {
        title: "Transit",
        category: "Solar System Dynamics & Planetary Terms",
        content: `
            <p><strong>Definition:</strong> When a smaller celestial body passes in front of a larger one.</p>
            <p><strong>Example:</strong> Capturing the ISS (International Space Station) Transit across the face of the Sun or Moon requires sub-millisecond shutter speeds and precise timing.</p>
        `
    },
    {
        title: "Ecliptic Plane",
        category: "Solar System Dynamics & Planetary Terms",
        content: `
            <p><strong>Definition:</strong> The imaginary plane defined by the Earth's orbit around the Sun. Most planets in our solar system stay within a few degrees of this line.</p>
            <p><strong>Example:</strong> If you are hunting for Saturn, you look along the Ecliptic; you will never find a major planet near the North Star (Polaris).</p>
        `
    },
    {
        title: "Chromatic Aberration (Color Fringing)",
        category: "Optical Aberrations",
        content: `
            <p><strong>Definition:</strong> An optical defect where a lens fails to focus all colors to the same convergence point, resulting in purple or blue "halos" around bright stars.</p>
            <p><strong>Example:</strong> A budget "Achromat" refractor will show heavy purple fringing on Vega, whereas your FLT132 APO uses triplet glass to eliminate this effect.</p>
        `
    },
    {
        title: "Coma",
        category: "Optical Aberrations",
        content: `
            <p><strong>Definition:</strong> An aberration common in Newtonian reflectors where stars at the edge of the field look like tiny comets pointing toward the center.</p>
            <p><strong>Example:</strong> Without a Coma Corrector, the stars in the corners of your M31 image will look "smeared," even if the center is perfectly sharp.</p>
        `
    },
    {
        title: "Field Curvature",
        category: "Optical Aberrations",
        content: `
            <p><strong>Definition:</strong> A natural property of lenses where the "plane of focus" is actually a curve. If the center is in focus, the edges are blurry.</p>
            <p><strong>Example:</strong> To get a "flat field" for a large sensor like the ASI2600, you must use a Field Flattener to push the focus back into a flat plane.</p>
        `
    },
    {
        title: "Spherical Aberration",
        category: "Optical Aberrations",
        content: `
            <p><strong>Definition:</strong> An effect where light rays hitting the edge of a curved mirror or lens focus at a different point than rays hitting the center, causing a soft, "glowy" image.</p>
            <p><strong>Example:</strong> If a telescope mirror is not polished to a perfect parabola, stars will never look like pinpoints; they will always have a slight "haze" around them.</p>
        `
    },
    {
        title: "Astigmatism",
        category: "Optical Aberrations",
        content: `
            <p><strong>Definition:</strong> An optical defect where the telescope focuses light into a line rather than a point, often caused by pinched optics or tilted elements.</p>
            <p><strong>Example:</strong> If you rack the focuser in and out, and the star turns from a horizontal oval to a vertical oval, your optical train has Astigmatism.</p>
        `
    },
    {
        title: "ASCOM (Astronomy Common Object Model)",
        category: "Software, Scripting & Automation",
        content: `
            <p><strong>Definition:</strong> The "universal language" for Windows that allows different astronomy software (like N.I.N.A.) to talk to different hardware (like your Losmandy G11).</p>
            <p><strong>Example:</strong> By installing the ASCOM Driver for your mount, you can control it from any software on your PC without needing proprietary apps for every device.</p>
        `
    },
    {
        title: "INDI (Instrument Neutral Distributed Interface)",
        category: "Software, Scripting & Automation",
        content: `
            <p><strong>Definition:</strong> The Linux equivalent of ASCOM, commonly used on Raspberry Pi-based controllers like the StellarMate or Astroberry.</p>
            <p><strong>Example:</strong> If you run your rig using a mini-PC at the telescope, INDI is likely the "traffic cop" managing the camera and mount commands.</p>
        `
    },
    {
        title: "Sequencing",
        category: "Software, Scripting & Automation",
        content: `
            <p><strong>Definition:</strong> The process of creating a list of commands for the rig to follow automatically (e.g., "Take 20 frames of Red, then 20 of Green, then park the mount").</p>
            <p><strong>Example:</strong> In N.I.N.A., you can build a "Sequence" that waits for the target to rise, focuses every 1 hour, and sends you a text message when the session is finished.</p>
        `
    },
    {
        title: "Guiding Rate",
        category: "Software, Scripting & Automation",
        content: `
            <p><strong>Definition:</strong> The speed at which the mount moves when receiving a correction from the autoguider, usually expressed as a fraction of "Sidereal" speed (e.g., 0.5x).</p>
            <p><strong>Example:</strong> If your guiding is "oscillating" (moving back and forth too fast), you might need to lower your Guiding Rate in the mount settings.</p>
        `
    },
    {
        title: "HFR (Half Flux Radius)",
        category: "Software, Scripting & Automation",
        content: `
            <p><strong>Definition:</strong> A mathematical measurement used by auto-focus software to determine star sharpness. It is more robust than FWHM for focusing.</p>
            <p><strong>Example:</strong> Your autofocus routine will take several shots, calculate the HFR for each, and move the motor until it finds the "V-curve" where the HFR is at its lowest (sharpest).</p>
        `
    }
];
